### ISSUE TITLE
After the first word, Trigger needs space before the trigger character it to initiate process.

### ISSUE THREAD

**Issue by anandphulwani** [avcs06/AutoSuggest#22]
Enviroment Details:
Windows 10
Firefox, Firefox Developer Edition

Situation: 
Trigger Character: "."
Use cases:
1. anand.
2. anand .

Expected Behaviour:  Use cases 1st and 2nd, both dropdown of suggestions should load.
Actual Behaviour: In Use case 1st it does not load and in the 2nd one it loads.

**Comment by anandphulwani** [comment]
To detail, i am trying to give suggestions for email address, i want to give suggestion after separator as well, my form already has firstname, middlename and lastname, i am using all three values as suggestions. so when i type down email like **anand.** i want to open up the suggestions box as well. I have made the following changes to make it work.

1. function SuggestionList(options)
`this.regex = new RegExp('(?:\\W+|^)' + escapedTrigger + '(\\S*)$');`
to 
`this.regex = new RegExp('(?:.*|^)' + escapedTrigger + '(\\S*)$');`
2. var setValue = function setValue(_ref)
`value = value.slice(0, 0 - currentValue.length - (trigger || '').length) + (suggestion.insertText || suggestion.insertHtml);`
to
`if (trigger) {`
`value = value.slice(0, 0 - currentValue.length - (trigger || '').length) + trigger + (suggestion.insertText || suggestion.insertHtml);`
`} else {`
`value = value.slice(0, 0 - currentValue.length - (trigger || '').length) + (suggestion.insertText || suggestion.insertHtml);`
`}`

However i have made changes to only **if (data(element, 'isInput'))** block, so no changes have been made for other controls like textarea and contenteditablebox.

**Comment by anandphulwani** [comment]
1. Also can you suggest how to use multiple triggers for the same suggestions.
2. Though i should thank you for such an amazing library, it really satisfies 90% of my requirements, but can you suggest some similar libraries which are more mature, actually i have to use it in production and really don't want to mess things up. hope you dont mind. Many thanks.

**Comment by chandrasekhar-ambula** [comment]
@anandphulwani

**For Case 1:** This is a conscious decision not a bug, any trigger followed by a non word character is considered trigger

non word character is any character excluding (a-zA-Z0-9_)

I have implemented it in this way because of the ability to mention any character as a trigger, if a user wants to mention a normal letter instead of a special character as a trigger, not implementing the current behavior will raise unexpected popups

For your use case, it will be better to support it with flag, and as you have already made some changes, you can send a PR. Else I will make the changes myself and will update the plugin over next weekend

For the flag I am thinking of using triggerAll | triggerAnywhere: Boolean, which if true will ignore the rule \W (for the flag if you can come up with a better name, you are welcome :D)

**For case 2:** Another conscious decision, if you want the trigger character also in the inserted value, insertText or insertHtml should have the character, by default trigger character will not be inserted. This is to support users who wants to use trigger char only for triggering but not in final output.

Anyone who wants the trigger character in the output can still achieve it by including it in the insertText or insertHtml

**Comment by chandrasekhar-ambula** [comment]
> 1. Also can you suggest how to use multiple triggers for the same suggestions.
> 2. Though i should thank you for such an amazing library, it really satisfies 90% of my requirements, but can you suggest some similar libraries which are more mature, actually i have to use it in production and really don't want to mess things up. hope you dont mind. Many thanks.

1. I didn't understand what you mean by this
2. This is one other plugin i know of https://github.com/zurb/tribute

will update you if i find anymore

**Comment by anandphulwani** [comment]
>     1. I didn't understand what you mean by this
As of now in the suggestions array we have **trigger** and **values** keys, currently we can set only one trigger for a set of values, for an e.g.

`trigger: '#',`

I was thinking if its possible to do something like this

`trigger: ['#','.','@'],`

Currently i have to copy the whole block for all the different triggers.

**Comment by avcs06** [comment]
This is easy to handle, you can have a common object for remaining values other than trigger and add 3 entries with 3 triggers, not a common usecase to add specific support
